# BUTTON         Value
#   L1             4
#   L2             6
#   R1             5
#   R2             7
#   A              1
#   B              2
#   X              0
#   Y              3

#    AXIS        Value
# Left Horiz.      0
# Left Vert.       1
# Right Horiz.     2
# Right Vert.      5
#    L2            3
#    R2            4
# D-pad Horiz.     9
# D-pad Vert.      10
# Accel x          7
# Accel y          6
# Accel z          8

# joy_teleop/teleop_twist_joy_node:
#   ros__parameters:
#     axis_linear:
#       x: 1
#     scale_linear:
#       x: 0.4
#     scale_linear_turbo:
#       x: 1.0
#     axis_angular:
#       yaw: 0
#     scale_angular:
#       yaw: 0.6
#     scale_angular_turbo:
#       yaw: 1.2
#     enable_button: 9
#     enable_turbo_button: 5
# joy_teleop/joy_node:
#   ros__parameters:
#     rate: 10.0
#     deadzone: 0.1
#     autorepeat_rate: 20.0
#     dev: /dev/input/js0


joy_teleop/teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.4 # 0.4 m/s
    scale_linear_turbo:
      x: 1.0 
    axis_angular:
      yaw: 0 # rad/s
    scale_angular:
      yaw: 1.8 # rad/s
    scale_angular_turbo:
      yaw: 2.4 # rad/s
    enable_button: 9
    enable_turbo_button: 5
joy_teleop/joy_node:
  ros__parameters:
    rate: 10.0
    deadzone: 0.1
    autorepeat_rate: 20.0
    dev: /dev/input/js0